### ISSUE TITLE
make deps/update warning

### ISSUE THREAD

**Issue by the-j0k3r** [silverwind/eslint-config-silverwind#2]
warning "eslint-config-silverwind > eslint-plugin-sonarjs@0.5.0" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".

Maybe these can be silenced somehow?

**Comment by silverwind** [comment]
No, yarn does not offer an option to silence these but this one is harmless, `eslint-plugin-sonarjs` is compatible with eslint 7, just has not officially updated yet.
